CREATE TABLE logs_v1
(
    `_timestamp` UInt64, -- Time this log was generated by the service
    `_service` String, -- What service generated this log (syslog, application name)
    `_host` String, -- Which host this log came from
    `_kind` LowCardinality(String), -- What kind of logs this is -> app (microservice log),system (iptables deny logs, ssh sessions)

    `message` String, -- log line equivalent, can be an entire json payload

    -- Key values
    `string.names`	Array(LowCardinality(String)),
	`string.values`	Array(String)
)

ENGINE = MergeTree()
ORDER BY (_timestamp, cityHash64(_service))
SAMPLE BY (cityHash64(_service))
PARTITION BY (toYYYYMM(FROM_UNIXTIME(toUInt64(_timestamp / 1000))), cityHash64(_service));
