// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Links        string
	SkippedLinks string
	Updates      string
}{
	Links:        "links",
	SkippedLinks: "skipped_links",
	Updates:      "updates",
}
