// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/jaxsax/projects/tapeworm/botv2/internal/config"
	"github.com/jaxsax/projects/tapeworm/botv2/internal/db"
	"github.com/jaxsax/projects/tapeworm/botv2/internal/dimension"
	"github.com/jaxsax/projects/tapeworm/botv2/internal/httpserver"
	"github.com/jaxsax/projects/tapeworm/botv2/internal/logging"
	"github.com/jaxsax/projects/tapeworm/botv2/internal/services/algolia"
	"github.com/jaxsax/projects/tapeworm/botv2/internal/services/content_block"
	"github.com/jaxsax/projects/tapeworm/botv2/internal/services/dim_collector"
	"github.com/jaxsax/projects/tapeworm/botv2/internal/telegrampoller"
)

// Injectors from wire.go:

func initialize() (*App, error) {
	options := config.ProvideHTTP()
	dbOptions := config.ProvideDB()
	loggingOptions := config.ProvideLogging()
	logger, err := logging.New(loggingOptions)
	if err != nil {
		return nil, err
	}
	store, err := db.Setup(dbOptions, logger)
	if err != nil {
		return nil, err
	}
	hn := algolia.NewForHN()
	hnCollector := dimension.NewHNCollector(hn)
	service := dimcollector.New(store, hnCollector)
	server := httpserver.New(options, store, logger, service)
	telegrampollerOptions := config.ProvideTelegram()
	contentblockService := contentblock.New(store)
	telegramPoller := telegrampoller.New(telegrampollerOptions, store, logger, contentblockService)
	app := &App{
		HTTPServer:     server,
		TelegramSource: telegramPoller,
		dimService:     service,
		Logger:         logger,
	}
	return app, nil
}
