// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/jaxsax/projects/tapeworm/botv2/internal/config"
	"github.com/jaxsax/projects/tapeworm/botv2/internal/logging"
)

import (
	_ "github.com/golang-migrate/migrate/v4/source/file"
)

// Injectors from wire.go:

func initialize() (*app, error) {
	options := config.ProvideDB()
	migrateOptions := config.ProvideMigrate()
	loggingOptions := config.ProvideLogging()
	logger, err := logging.New(loggingOptions)
	if err != nil {
		return nil, err
	}
	mainApp := &app{
		dbOptions:      options,
		migrateOptions: migrateOptions,
		logger:         logger,
	}
	return mainApp, nil
}
