load("@tapeworm_import//:requirements.bzl", "requirement")

py_binary(
    name = "main",
    srcs = ["main.py"],
    deps = [
        requirement("Flask"),
        requirement("Werkzeug"),
        requirement("MarkupSafe"),
        requirement("Jinja2"),
        requirement("itsdangerous"),
        requirement("Click")
    ]
)
